name: 'Terraform (test print)'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform test job'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print and wait with PowerShell
        run: |
          Write-Host "Hello from GitHub Actions using PowerShell!"
          Write-Host "Sleeping for 10 seconds..."
          Start-Sleep -Seconds 10
          Write-Host "Done sleeping." -f green
